version: 1.1.2.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: v141
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: v140
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      TOOLSET: v120

configuration:
- Debug
- Release

platform:
- x86
- x64
- ARM

build_script:
- ps: >
    msbuild "C:\projects\t1ha\t1ha.sln" /verbosity:minimal
    /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    /property:PlatformToolset=$env:TOOLSET
    /property:Configuration=$env:CONFIGURATION
    /property:Platform=$env:PLATFORM

test_script:
- ps: |
    if (($env:PLATFORM -eq "x86") -and (Test-Path "C:\projects\t1ha\Win32\$env:CONFIGURATION\t1ha-test\t1ha-test.exe" -PathType Leaf)) {
      & "C:\projects\t1ha\Win32\$env:CONFIGURATION\t1ha-test\t1ha-test.exe"
    } elseif (($env:PLATFORM -ne "ARM") -and ($env:PLATFORM -ne "ARM64")) {
      & "C:\projects\t1ha\$env:PLATFORM\$env:CONFIGURATION\t1ha-test\t1ha-test.exe"
    }
